"""Agrega columnas archivo_url y estado

Revision ID: 1f75e56f03bd
Revises: 
Create Date: 2025-05-11 23:04:44.239192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f75e56f03bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('archivo_url')

    # ### end Alembic commands ###
